export const sites = [
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },

  { name: "Celestial Rhapsody", url: "#" },
  { name: "Ripples of Resilience", url: "#" },
  { name: "Echoes of Eternity", url: "#" },
  { name: "Chromatic Dreamscape", url: "#" },
  { name: "Metamorphosis of Light", url: "#" },
  { name: "Suspended Symphony", url: "#" },
  { name: "Enigmatic Embrace", url: "#" },
  { name: "Infinite Horizons", url: "#" },
  { name: "Whimsical Reverie", url: "#" },
  { name: "Harmony in Chaos", url: "#" },
  { name: "Temporal Fragments", url: "#" },
  { name: "Journey to the Unknown", url: "#" },
  { name: "Serenade of Shadows", url: "#" },
  { name: "Transcendent Fusion", url: "#" },
  { name: "Reflections of Tomorrow", url: "#" },
  { name: "Vivid Solitude", url: "#" },
  { name: "Mystical Melancholy", url: "#" },
  { name: "Sculpted Silence", url: "#" },
  { name: "Dance of the Cosmos", url: "#" },
  { name: "Abstract Elegance", url: "#" },
];
