export const sites = [
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "New ArtWork",
    text: "New art description here",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Gunnar Aagaard Andersen's Lysgrafik",
    text: "Gunnar Aagaard Andersen, en mester af lys og form, var en banebrydende dansk kunstner, hvis værker fortsætter med at fortrylle og inspirere i dag. Hans eksperimenter med lysgrafik udgør et fængslende kapitel i kunsthistorien. I midten af det 20. århundrede begyndte Andersen at udforske lys som et medium i kunsten. Han greb fat i lyskilden som sin pensel og mesterligt manipulerede det for at skabe betagende visuelle oplevelser. Hans mesterværk, Lysgrafik, er et monument over hans tekniske dygtighed og kunstneriske geni. I dette værk forener Andersen lys og rum på en måde, der forvandler det omgivende miljø. Gennem subtile variationer af lysintensitet, farver og former skaber han en stemning, der er både meditativ og forunderlig. Betragteren drages ind i et skiftende landskab af lys og skygge, hvor kontraster og mønstre danser i en elegant symfoni.",
    js_file_name: "gunnarAagaardAndersen.js",
    og_img_file_name: "gunnarAagaardAndersen_original.png",
    mod_img_file_name: "gunnarAagaardAndersen_art.png",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  /*   { name: "Celestial Rhapsody" },
  { name: "Ripples of Resilience" },
  { name: "Echoes of Eternity" },
  { name: "Chromatic Dreamscape" },
  { name: "Metamorphosis of Light" },
  { name: "Suspended Symphony" },
  { name: "Enigmatic Embrace" },
  { name: "Infinite Horizons" },
  { name: "Whimsical Reverie" },
  { name: "Harmony in Chaos" },
  { name: "Temporal Fragments" },
  { name: "Journey to the Unknown" },
  { name: "Serenade of Shadows" },
  { name: "Transcendent Fusion" },
  { name: "Reflections of Tomorrow" },
  { name: "Vivid Solitude" },
  { name: "Mystical Melancholy" },
  { name: "Sculpted Silence" },
  { name: "Dance of the Cosmos" },
  { name: "Abstract Elegance" }, */
];
