export const sites = [
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "New ArtWork",
    text: "New art description here",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Urban Serenity",
    text: "Urban Serenity intricately captures the essence of a bustling city while seamlessly interweaving moments of tranquility within its vibrant composition. \n \n The artist, deeply inspired by the dynamic urban landscape, skillfully merged contrasting elements to evoke a sense of both energy and calm. Using a blend of bold brushstrokes and a diverse palette of acrylics, the artist depicted the city's liveliness with vivid colors and dynamic textures.",
    js_file_name: "urban_serenity.js",
    og_img_file_name: "urban_serenity_original.jpg",
    mod_img_file_name: "urban_serenity_art.PNG",
  },
  {
    name: "Fabriksbillede 2.0.5.0 ",
    text: "Fabriksbillede 2.0.5.0 er et futuristisk kunstværk, der fusionerer new media art og abstrakt konstruktivisme. Stærkt inspireret af Preben Hornungs Fabriksbillede fra 1949, udforsker dette værk samme problemstilling med industri og masseproduktion, med fra nutidens perspektiv og stiller spørgsmålet: Er en bæredygtig industri realistisk og opnåelig? Værket inviterer beskueren til at deltage i skabelsen af en visionær fabrik, men udfordrer opfattelsen af, hvorvidt en fuldstændig grøn fabrik er realistisk, og om skyggerne af forurening vil forblive. Fabriksbillede 2.0.5.0 ansporer beskueren til at reflektere over vores kollektive ansvar for at forme en bæredygtig fremtid. Dette kunstværk er ikke blot et visuelt udtryk; det er en interaktiv samtale om, hvorvidt vi kan opnå et klimaneutralt samfund inden 2050. Gennem kunstens prisme inviteres vi til en dialog bæredygtighed og miljømæssig bevidsthed.",
    js_file_name: "Fabriksbillede.js",
    og_img_file_name: "Fabriksbillede_orginal.jpg",
    mod_img_file_name: "Fabriksbillede2050.png",
  },
  /*   { name: "Celestial Rhapsody" },
  { name: "Ripples of Resilience" },
  { name: "Echoes of Eternity" },
  { name: "Chromatic Dreamscape" },
  { name: "Metamorphosis of Light" },
  { name: "Suspended Symphony" },
  { name: "Enigmatic Embrace" },
  { name: "Infinite Horizons" },
  { name: "Whimsical Reverie" },
  { name: "Harmony in Chaos" },
  { name: "Temporal Fragments" },
  { name: "Journey to the Unknown" },
  { name: "Serenade of Shadows" },
  { name: "Transcendent Fusion" },
  { name: "Reflections of Tomorrow" },
  { name: "Vivid Solitude" },
  { name: "Mystical Melancholy" },
  { name: "Sculpted Silence" },
  { name: "Dance of the Cosmos" },
  { name: "Abstract Elegance" }, */
];
